name: 'Transfer issues with labels'
description:
  'Transfer issues between repositories using labels, including private to
  public transfers.'
author: 'fgerthoffert'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: activity
  color: green

# Define your inputs here.
inputs:
  token:
    description: 'A GitHub Personal API Token'
    required: true
  router_prefix:
    description:
      'Label prefix to identify where to transfer the issue (for example,
      "transfer:")'
    required: true
    default: 'transfer:'
  allow_private_public_transfer:
    description:
      'Allow issues to be transferred from private to public repositories.'
    default: false
  allow_private_public_transfer_comment:
    description:
      'Once an issue is transferred from a private to a public repository, a
      comment will be added to the issue detailing the repositories.'
    default: false
  create_labels_if_missing:
    description: 'Create labels in the destination repository if missing'
    default: true
  github_issue_id:
    description:
      'When providing a GitHub Issue ID (GraphQL ID) the action will use that ID
      instead of the one provided in the event payload.'
    required: false

outputs:
  issue_id:
    description: 'Issue ID of the transferred issue'

runs:
  using: node20
  main: dist/index.js
